TRUSTED_PRODUCT_CATALOG = [
    {
        "brand": "Lovevery",
        "title": "Wooden posting and object permanence box",
        "age_min": 12,
        "age_max": 24,
        "materials": ["FSC wood", "water-based finishes"],
        "certifications": ["CPSIA-aligned brand standards"],
        "milestones": [
            "Puts something in a container, like a block in a cup",
            "Stacks at least two small objects, like blocks",
        ],
        "search_terms": "Lovevery wooden object permanence box",
        "overstimulation_risk": "Low",
        "small_parts_note": "Use only age-labeled toddler pieces and supervise play.",
    },
    {
        "brand": "Hape",
        "title": "Wooden spoon and bowl set",
        "age_min": 12,
        "age_max": 30,
        "materials": ["wood", "water-based finishes"],
        "certifications": ["ASTM-style toy safety positioning"],
        "milestones": [
            "Tries to use a spoon",
            "Drinks from a cup without a lid and may spill sometimes",
            "Feeds themself with fingers",
        ],
        "search_terms": "Hape wooden toddler spoon bowl set",
        "overstimulation_risk": "Low",
        "small_parts_note": "Choose full-size toddler utensils, not miniature dollhouse pieces.",
    },
    {
        "brand": "PlanToys",
        "title": "Wooden stacking and sorting set",
        "age_min": 12,
        "age_max": 30,
        "materials": ["rubberwood", "water-based dyes"],
        "certifications": ["Sustainable wood brand standards"],
        "milestones": [
            "Stacks at least two small objects, like blocks",
            "Plays with more than one toy at the same time",
            "Puts something in a container, like a block in a cup",
        ],
        "search_terms": "PlanToys wooden toddler stacking sorting toy",
        "overstimulation_risk": "Low",
        "small_parts_note": "Avoid sets with pieces smaller than the child's mouth.",
    },
    {
        "brand": "Melissa & Doug",
        "title": "Wooden chunky puzzle",
        "age_min": 12,
        "age_max": 36,
        "materials": ["wood", "painted finishes"],
        "certifications": ["US toy safety testing program"],
        "milestones": [
            "Looks at a familiar object when you name it",
            'Points to things in a book when asked, like "Where is the bear?"',
            "Uses more gestures than waving and pointing",
        ],
        "search_terms": "Melissa and Doug wooden chunky puzzle toddler",
        "overstimulation_risk": "Low",
        "small_parts_note": "Prefer chunky knobs and large pieces for toddlers under 3.",
    },
    {
        "brand": "Bannor Toys",
        "title": "Personalized wooden name puzzle",
        "age_min": 18,
        "age_max": 36,
        "materials": ["hardwood", "non-toxic finish"],
        "certifications": ["Small-batch US maker standards"],
        "milestones": [
            "Scribbles",
            "Holds something in one hand while using the other hand",
            "Tries to use switches, knobs, or buttons on a toy",
        ],
        "search_terms": "Bannor Toys wooden name puzzle toddler",
        "overstimulation_risk": "Low",
        "small_parts_note": "Use under supervision if letters are removable.",
    },
    {
        "brand": "Tender Leaf Toys",
        "title": "Wooden pretend kitchen food set",
        "age_min": 24,
        "age_max": 36,
        "materials": ["wood", "water-based paints"],
        "certifications": ["EN71-style toy safety positioning"],
        "milestones": [
            "Plays with toys in a simple way, like pushing a toy car",
            "Plays with more than one toy at the same time",
            "Copies you doing chores, like sweeping with a broom",
        ],
        "search_terms": "Tender Leaf Toys wooden pretend food toddler",
        "overstimulation_risk": "Low",
        "small_parts_note": "Check individual set age labels before buying.",
    },
    {
        "brand": "Manhattan Toy",
        "title": "Wooden clutching and bead toy",
        "age_min": 6,
        "age_max": 18,
        "materials": ["wood", "water-based finishes"],
        "certifications": ["Infant toy safety testing program"],
        "milestones": [
            "Picks things up between thumb and pointer finger",
            "Shows you an object they like",
        ],
        "search_terms": "Manhattan Toy wooden clutching toddler toy",
        "overstimulation_risk": "Low",
        "small_parts_note": "Choose one-piece clutching toys with no removable beads.",
    },
    {
        "brand": "Uncle Goose",
        "title": "Embossed wooden alphabet blocks",
        "age_min": 18,
        "age_max": 36,
        "materials": ["basswood", "non-toxic inks"],
        "certifications": ["US-made toy safety standards"],
        "milestones": [
            "Stacks at least two small objects, like blocks",
            "Says at least two words together, like \"More milk\"",
            "Points to at least two body parts when asked",
        ],
        "search_terms": "Uncle Goose wooden alphabet blocks toddler",
        "overstimulation_risk": "Low",
        "small_parts_note": "Blocks are better for supervised floor play than crib use.",
    },
]


TRUSTED_BRANDS = {product["brand"].lower(): product for product in TRUSTED_PRODUCT_CATALOG}
